---
- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present

- name: Add MySQL APT repository
  apt_repository:
    repo: deb http://repo.mysql.com/apt/ubuntu/ {{ ansible_distribution_release }} mysql-8.0
    state: present

- name: Import MySQL GPG key
  apt_key:
    url: https://dev.mysql.com/doc/guides/release-notes/release-key-8.asc
    state: present

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
    update_cache: yes
  register: mysql_installed

- name: Template MySQL configuration file
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify: Restart MySQL

- name: Enable MySQL service on boot
  service:
    name: mysql
    enabled: yes
